-- ZPause's settings, from the lobby: the BOIII and T7x builds.
--
-- Generated by tools/mk_t7_uiscripts.py from the Workshop build's
-- ui/zpause/zpausesettings.lua, with one line changed -- the require below,
-- which a ui_script asks for by bare name. Never edit by hand: an edit here
-- would be undone by the next build, and the two menus would drift apart.
--
-- Dropped in as <client>/ui_scripts/zpause/__init__.lua, which the client
-- runs inside the game's own LUI. It keeps the frontend guard it was
-- written with, the same test the clients' own ui_scripts open on.
--
-- A setting saved here goes into the class names of the offline zombies
-- loadouts, as it does on the Workshop build -- but with no mod loaded that
-- is the player's own file rather than a mod's copy. Zombies has no
-- create-a-class, so nothing in a zombies game reads them.

if Engine.GetCurrentMap() ~= "core_frontend" then
	return
end

require( "zpausesettingsdata" )

local Z = CoD.ZPauseSettings
Z.saved = {}
Z.dirty = false
Z.ByKey = {}
for _, page in ipairs( Z.Pages ) do
	for _, row in ipairs( page.rows ) do
		Z.ByKey[row.key] = row
	end
end

-- ------------------------------------------------------------------------
-- Settings
-- ------------------------------------------------------------------------

-- Whether the value a dvar holds is the one a choice stands for, numbers
-- compared as numbers: "0.30" is 0.3.
Z.Same = function ( a, b )
	local na = tonumber( a )
	local nb = tonumber( b )
	if na ~= nil and nb ~= nil then
		return na == nb
	end
	return a == b
end

-- Whether a setting is still at its default. Empty is the obvious case, but
-- the script writes every default into its dvar as a match loads, so after
-- one has been played every setting nobody touched holds its default.
Z.IsDefault = function ( current, row )
	return current == "" or Z.Same( current, row.default )
end

Z.Get = function ( dvar )
	local ok, value = pcall( Engine.DvarString, nil, dvar )
	if ok and type( value ) == "string" then
		return value
	end
	return ""
end

-- Engine.SetDvar is what the game's own settings pages use. Where that did
-- not take, the console's set does it: set is how a dvar that nothing has
-- made yet comes to exist.
Z.Set = function ( controller, dvar, value )
	pcall( Engine.SetDvar, dvar, value )
	if Z.Get( dvar ) ~= value then
		Engine.Exec( controller, "set " .. dvar .. " \"" .. value .. "\"" )
	end
end

-- ------------------------------------------------------------------------
-- Saving
--
-- A mod keeps save files of its own -- players/mods/<folder>/ for a local
-- mod, players/311210/<item>/ for a Workshop item -- and a choice made here
-- goes into this mod's copy of the offline zombies loadouts, in the class
-- names: zombies has no create-a-class, so nothing in a zombies game reads
-- them. What is written is "ZP1" and then five characters for each setting
-- that is not at its default: three naming the setting and two naming its
-- value. The build makes both from the names themselves, so a setting or a
-- choice added in a later version leaves the ones already saved alone.
-- ------------------------------------------------------------------------

Z.STORAGE = Enum.StorageFileType.STORAGE_ZM_LOADOUTS_OFFLINE
Z.FORMAT = "ZP1"
Z.ENTRY = 5

Z.Fields = function ( controller )
	local fields = {}
	pcall( function ()
		local names = Engine.StorageGetBuffer( controller, Z.STORAGE ).cacLoadouts.customClassName
		for index = 0, 31 do
			local field = names[index]
			if field == nil then
				return
			end
			table.insert( fields, field )
		end
	end )
	return fields
end

-- How many characters a class name holds, found by asking it: a name longer
-- than that comes back shorter, or is refused.
Z.Room = function ( field )
	local keep = field:get() or ""
	local room = 0
	for _, size in ipairs( {
		64,
		32,
		24,
		16,
		12,
		8
	} ) do
		if pcall( field.set, field, string.rep( "0", size ) ) then
			local got = field:get()
			if type( got ) == "string" and string.len( got ) > 0 then
				room = math.min( size, string.len( got ) )
				break
			end
		end
	end
	pcall( field.set, field, keep )
	return room
end

-- dvar -> value, for every setting saved away from its default.
Z.Read = function ( controller )
	local text = ""
	for _, field in ipairs( Z.Fields( controller ) ) do
		local part = field:get()
		if type( part ) ~= "string" or part == "" then
			break
		end
		text = text .. part
	end
	local saved = {}
	if string.sub( text, 1, string.len( Z.FORMAT ) ) ~= Z.FORMAT then
		return saved
	end
	for at = string.len( Z.FORMAT ) + 1, string.len( text ) - Z.ENTRY + 1, Z.ENTRY do
		local row = Z.ByKey[string.sub( text, at, at + 2 )]
		if row ~= nil then
			local valueKey = string.sub( text, at + 3, at + 4 )
			for index, key in ipairs( row.keys ) do
				if key == valueKey then
					saved[row.dvar] = row.values[index]
				end
			end
		end
	end
	return saved
end

Z.Write = function ( controller )
	local fields = Z.Fields( controller )
	if #fields == 0 then
		return false
	end
	local room = Z.Room( fields[1] )
	if room == 0 then
		return false
	end
	local text = Z.FORMAT
	for _, page in ipairs( Z.Pages ) do
		for _, row in ipairs( page.rows ) do
			local value = Z.saved[row.dvar]
			if value ~= nil then
				for index, known in ipairs( row.values ) do
					if known == value and string.len( text ) + Z.ENTRY <= room * #fields then
						text = text .. row.key .. row.keys[index]
					end
				end
			end
		end
	end
	for index, field in ipairs( fields ) do
		local from = (index - 1) * room + 1
		pcall( field.set, field, string.sub( text, from, from + room - 1 ) )
	end
	Engine.StorageWrite( controller, Z.STORAGE )
	return true
end

-- Saved when a page closes, not on every press.
Z.Flush = function ( controller )
	if Z.dirty then
		Z.dirty = false
		pcall( Z.Write, controller )
	end
end

-- Once a game: what was saved goes back into the dvars the first time the
-- frontend starts with this mod loaded, and not again after a match, so a
-- change the host made from the pause menu lasts until the game closes, the
-- same as one typed into the console.
Z.Startup = function ( controller )
	if not Z.dirty then
		Z.saved = Z.Read( controller )
	end
	if Z.Get( "zp_lobby_restored" ) ~= "1" then
		for dvar, value in pairs( Z.saved ) do
			Z.Set( controller, dvar, value )
		end
		Z.Set( controller, "zp_lobby_restored", "1" )
	end
end

-- The save files are read a moment after the frontend starts, so this looks
-- once a second until they are in -- or, after a minute of the game not
-- saying so, reads them anyway.
Z.Wait = function ( parent, tries )
	parent:addElement( LUI.UITimer.newElementTimer( 1000, true, function ()
		Z.Hook()
		local controller = Engine.GetPrimaryController()
		if controller ~= nil and controller >= 0 then
			local ok, ready = pcall( Engine.StorageIsFileReady, controller, Z.STORAGE )
			if ok and ready == true or tries >= 60 then
				Z.Startup( controller )
				return
			end
			tries = tries + 1
		end
		Z.Wait( parent, tries )
	end ) )
end

-- ------------------------------------------------------------------------
-- The button
-- ------------------------------------------------------------------------

Z.IsHost = function ( controller )
	local ok, host = pcall( function ()
		local root = DataSources.LobbyRoot.getModel( controller )
		local model = nil
		if Engine.IsLobbyActive( Enum.LobbyType.LOBBY_TYPE_GAME ) then
			model = Engine.GetModel( root, "gameClient.isHost" )
		else
			model = Engine.GetModel( root, "privateClient.isHost" )
		end
		if model == nil then
			return 1
		end
		return Engine.GetModelValue( model )
	end )
	return ok and host == 1
end

-- In its own group, before the gum and build kit buttons every zombies lobby
-- ends with.
Z.AddButton = function ( buttons )
	local at = #buttons + 1
	for index, button in ipairs( buttons ) do
		if button.optionDisplay == "MENU_BUBBLEGUM_BUFFS_CAPS" then
			at = index
			break
		end
	end
	if at > 1 then
		buttons[at - 1].isLastButtonInGroup = true
	end
	table.insert( buttons, at, {
		optionDisplay = "ZPAUSE SETTINGS",
		action = Z.OpenFromLobby,
		customId = "btnZPauseSettings",
		isLargeButton = true,
		isLastButtonInGroup = true,
		disabled = false,
		selected = false,
		warning = false
	} )
end

-- The zombies lobbies a host starts a game from: online, where solo games
-- start, private, and LAN.
Z.Hook = function ()
	if Z.hooked or CoD.LobbyMenus == nil or CoD.LobbyMenus.AddButtonsForTarget == nil or LobbyData == nil or LobbyData.UITargets == nil then
		return
	end
	Z.hooked = true
	Z.Lobbies = {}
	for _, name in ipairs( {
		"UI_ZMLOBBYONLINE",
		"UI_ZMLOBBYONLINECUSTOMGAME",
		"UI_ZMLOBBYLANGAME"
	} ) do
		local target = LobbyData.UITargets[name]
		if target ~= nil then
			Z.Lobbies[target.id] = true
		end
	end
	local addButtonsForTarget = CoD.LobbyMenus.AddButtonsForTarget
	CoD.LobbyMenus.AddButtonsForTarget = function ( controller, id )
		local buttons = addButtonsForTarget( controller, id )
		if Z.Lobbies[id] and Z.IsHost( controller ) then
			Z.AddButton( buttons )
		end
		return buttons
	end
end

-- Opened the way the game opens its own bot settings from the lobby, so the
-- rest of the lobby sees the host is changing the rules.
Z.OpenFromLobby = function ( self, element, controller, param, menu )
	pcall( function ()
		CoD.LobbyBase.SetLeaderActivity( controller, CoD.LobbyBase.LeaderActivity.EDITING_GAME_RULES )
	end )
	local opened = OpenOverlay( menu, "ZPauseSettings", controller )
	if opened ~= nil then
		LUI.OverrideFunction_CallOriginalFirst( opened, "close", function ()
			pcall( function ()
				CoD.LobbyBase.ResetLeaderActivity( controller )
			end )
		end )
	end
end

-- ------------------------------------------------------------------------
-- The pages
-- ------------------------------------------------------------------------

-- The frame every page shares: the game's own game settings background, with
-- its title and the pane saying what the thing under the cursor does.
Z.NewPage = function ( controller, name, title )
	require( "ui.uieditor.widgets.GameSettings.GameSettings_Background" )
	local self = CoD.Menu.NewForUIEditor( name )
	self.disablePopupOpenCloseAnim = true
	self.soundSet = "ChooseDecal"
	self:setOwner( controller )
	self:setLeftRight( true, true, 0, 0 )
	self:setTopBottom( true, true, 0, 0 )
	self:playSound( "menu_open", controller )
	self.buttonModel = Engine.CreateModel( Engine.GetModelForController( controller ), name .. ".buttonPrompts" )
	self.anyChildUsesUpdateState = true

	local background = CoD.GameSettings_Background.new( self, controller )
	background:setLeftRight( true, true, 0, 0 )
	background:setTopBottom( true, true, 0, 0 )
	pcall( function ()
		background.MenuFrame.titleLabel:setText( title )
		background.MenuFrame.cac3dTitleIntermediary0.FE3dTitleContainer0.MenuTitle.TextBox1.Label0:setText( title )
		background.GameSettingsSelectedItemInfo.GameModeInfo:setAlpha( 0 )
		background.GameSettingsSelectedItemInfo.GameModeName:setAlpha( 0 )
	end )
	self:addElement( background )
	self.GameSettingsBackground = background

	self:AddButtonCallbackFunction( self, controller, Enum.LUIButton.LUI_KEY_XBB_PSCIRCLE, nil, function ( element, menu, controller, model )
		GoBack( self, controller )
		ClearSavedState( self, controller )
		return true
	end, function ( element, menu, controller )
		CoD.Menu.SetButtonLabel( menu, Enum.LUIButton.LUI_KEY_XBB_PSCIRCLE, "MENU_BACK" )
		return true
	end, false )
	background.MenuFrame:setModel( self.buttonModel, controller )
	return self
end

Z.FinishPage = function ( self, controller, name, onClose )
	self.Options.id = "Options"
	self:processEvent( {
		name = "menu_loaded",
		controller = controller
	} )
	self:processEvent( {
		name = "update_state",
		menu = self
	} )
	if not self:restoreState() then
		self.Options:processEvent( {
			name = "gain_focus",
			controller = controller
		} )
	end
	LUI.OverrideFunction_CallOriginalSecond( self, "close", function ( element )
		onClose( controller )
		element.GameSettingsBackground:close()
		element.Options:close()
		Engine.UnsubscribeAndFreeModel( Engine.GetModel( Engine.GetModelForController( controller ), name .. ".buttonPrompts" ) )
	end )
	return self
end

-- The first page: one button per page of settings, and the reset.
LUI.createMenu.ZPauseSettings = function ( controller )
	require( "ui.uieditor.widgets.Lobby.Common.List1ButtonLarge_PH" )
	DataSources.ZPauseSettingsPages = DataSourceHelpers.ListSetup( "ZPauseSettingsPages", function ( controller )
		local items = {}
		for index, page in ipairs( Z.Pages ) do
			table.insert( items, {
				models = {
					displayText = page.title
				},
				properties = {
					title = page.title,
					desc = page.hint,
					action = function ( self, element, controller, param, menu )
						OpenPopup( menu, "ZPauseSettingsPage" .. index, controller )
					end
				}
			} )
		end
		table.insert( items, {
			models = {
				displayText = "RESET TO DEFAULTS"
			},
			properties = {
				title = "RESET TO DEFAULTS",
				desc = "Put every setting on these pages back to DEFAULT.",
				action = Z.AskReset
			}
		} )
		return items
	end, true )

	local self = Z.NewPage( controller, "ZPauseSettings", "ZPAUSE SETTINGS" )
	SetPerControllerTableProperty( controller, "disableGameSettingsOptions", true )

	local count = #Z.Pages + 1
	local Options = LUI.UIList.new( self, controller, 4, 0, nil, false, false, 0, 0, false, false )
	Options:makeFocusable()
	Options:setLeftRight( true, false, 64, 344 )
	Options:setTopBottom( true, false, 135, 135 + count * 36 )
	Options:setWidgetType( CoD.List1ButtonLarge_PH )
	Options:setVerticalCount( count )
	Options:setSpacing( 4 )
	Options:setDataSource( "ZPauseSettingsPages" )
	if CoD.useMouse then
		Options:setHandleMouse( true )
	end
	Options:registerEventHandler( "list_item_gain_focus", function ( element, event )
		UpdateInfoModels( element )
	end )
	Options:registerEventHandler( "gain_focus", function ( element, event )
		local result = nil
		if element.gainFocus then
			result = element:gainFocus( event )
		elseif element.super.gainFocus then
			result = element.super:gainFocus( event )
		end
		CoD.Menu.UpdateButtonShownState( element, self, controller, Enum.LUIButton.LUI_KEY_XBA_PSCROSS )
		return result
	end )
	Options:registerEventHandler( "lose_focus", function ( element, event )
		local result = nil
		if element.loseFocus then
			result = element:loseFocus( event )
		elseif element.super.loseFocus then
			result = element.super:loseFocus( event )
		end
		return result
	end )
	self:AddButtonCallbackFunction( Options, controller, Enum.LUIButton.LUI_KEY_XBA_PSCROSS, "ENTER", function ( element, menu, controller, model )
		ProcessListAction( self, element, controller )
		return true
	end, function ( element, menu, controller )
		CoD.Menu.SetButtonLabel( menu, Enum.LUIButton.LUI_KEY_XBA_PSCROSS, "MENU_SELECT" )
		return true
	end, false )
	self:addElement( Options )
	self.Options = Options

	return Z.FinishPage( self, controller, "ZPauseSettings", function ( controller )
		SetPerControllerTableProperty( controller, "disableGameSettingsOptions", nil )
		Z.Flush( controller )
	end )
end

-- Called by a row whenever one of its choices is under the cursor: as the
-- page opens, as the cursor moves onto the row, and as left or right moves
-- the choice. Only a move to a different value is a change.
Z.Chosen = function ( self, element, controller, row, menu )
	UpdateInfoModels( element )
	local current = Z.Get( row.dvar )
	if element.default == true then
		if Z.IsDefault( current, row ) then
			return
		end
	elseif Z.Same( current, element.value ) then
		return
	end
	Z.Set( controller, row.dvar, element.value )
	if element.default == true then
		Z.saved[row.dvar] = nil
	else
		Z.saved[row.dvar] = element.value
	end
	Z.dirty = true
end

-- The game marks a setting that is not at its default; DEFAULT is the one
-- choice that is.
Z.ShowChange = function ( item )
	return item.default ~= true
end

-- One setting. DEFAULT is the empty value, and it stands for the default
-- itself, which is not offered again as a choice of its own. A value the page
-- does not step through keeps a choice of its own rather than showing as
-- another.
Z.Row = function ( row, source )
	local current = Z.Get( row.dvar )
	local atDefault = Z.IsDefault( current, row )
	local listed = atDefault
	for _, value in ipairs( row.values ) do
		if Z.Same( current, value ) then
			listed = true
		end
	end

	local options = {}
	local add = function ( label, value, isDefault, selected )
		table.insert( options, {
			models = {
				text = label
			},
			properties = {
				title = row.dvar,
				desc = row.hint,
				value = value,
				default = isDefault,
				actionParam = row,
				action = Z.Chosen,
				selectIndex = selected,
				loopEdges = false,
				showChangeIndicator = Z.ShowChange
			}
		} )
	end

	add( "DEFAULT", "", true, atDefault )
	for index, value in ipairs( row.values ) do
		if not Z.Same( value, row.default ) then
			if not listed and row.kind == "number" and tonumber( current ) ~= nil and tonumber( current ) < tonumber( value ) then
				add( current, current, false, true )
				listed = true
			end
			add( row.labels[index], value, false, not atDefault and Z.Same( current, value ) )
		end
	end
	if not listed then
		add( string.upper( current ), current, false, true )
	end
	options[1].properties.first = true
	options[#options].properties.last = true

	DataSources[source] = DataSourceHelpers.ListSetup( source, function ( controller )
		return options
	end, nil, nil, nil )
	return {
		models = {
			name = row.dvar,
			desc = row.hint,
			optionsDatasource = source
		},
		properties = {}
	}
end

-- A page of settings: the game's own settings list, the one its bot and
-- game rule pages use.
Z.NewSettingsPage = function ( controller, index )
	require( "ui.uieditor.widgets.Competitive.Competitive_SettingsList" )
	local page = Z.Pages[index] or Z.Pages[1]
	local name = "ZPauseSettingsPage" .. index
	DataSources[name] = DataSourceHelpers.ListSetup( name, function ( controller )
		local rows = {}
		for rowIndex, row in ipairs( page.rows ) do
			table.insert( rows, Z.Row( row, name .. "_" .. rowIndex ) )
		end
		return rows
	end, nil, nil, nil )

	local self = Z.NewPage( controller, name, page.title )
	SetPerControllerTableProperty( controller, "disableGameSettingsOptions", true )

	local Options = CoD.Competitive_SettingsList.new( self, controller )
	Options:setLeftRight( true, false, 26, 741 )
	Options:setTopBottom( true, false, 135, 720 )
	Options.Title.DescTitle:setText( page.title )
	Options.ButtonList:setVerticalCount( 15 )
	Options.ButtonList:setDataSource( name )
	self:addElement( Options )
	self.Options = Options

	return Z.FinishPage( self, controller, name, function ( controller )
		Z.Flush( controller )
	end )
end

for index = 1, #Z.Pages do
	LUI.createMenu["ZPauseSettingsPage" .. index] = function ( controller )
		return Z.NewSettingsPage( controller, index )
	end
end

-- ------------------------------------------------------------------------
-- Reset
-- ------------------------------------------------------------------------

-- Every setting the pages show, back to DEFAULT: the same empty value picking
-- DEFAULT on each one writes.
Z.ResetAll = function ( controller )
	for _, page in ipairs( Z.Pages ) do
		for _, row in ipairs( page.rows ) do
			Z.Set( controller, row.dvar, "" )
		end
	end
	Z.saved = {}
	Z.dirty = true
	Z.Flush( controller )
end

-- Asked first, the way the game asks before anything it cannot take back,
-- with NO under the cursor.
Z.AskReset = function ( self, element, controller, param, menu )
	CoD.OverlayUtility.AddSystemOverlay( "ZPauseSettingsReset", {
		menuName = "SystemOverlay_Compact",
		title = "RESET TO DEFAULTS",
		description = "Put every ZPause setting back to its default?",
		categoryType = CoD.OverlayUtility.OverlayTypes.Alert,
		listDatasource = function ()
			DataSources.ZPauseSettingsReset_List = DataSourceHelpers.ListSetup( "ZPauseSettingsReset_List", function ( controller )
				return {
					{
						models = {
							displayText = Engine.Localize( "MENU_NO" )
						},
						properties = {
							action = function ( self, element, controller, param, menu )
								GoBack( menu, controller )
							end
						}
					},
					{
						models = {
							displayText = Engine.Localize( "MENU_YES" )
						},
						properties = {
							action = function ( self, element, controller, param, menu )
								Z.ResetAll( controller )
								GoBack( menu, controller )
							end
						}
					}
				}
			end, true, nil )
			return "ZPauseSettingsReset_List"
		end
	} )
	CoD.OverlayUtility.CreateOverlay( controller, menu, "ZPauseSettingsReset" )
end

-- ------------------------------------------------------------------------

Z.Hook()
if LUI.roots ~= nil and LUI.roots.UIRootFull ~= nil then
	Z.Wait( LUI.roots.UIRootFull, 0 )
end
