-- Generated by tools/mk_t7_lobby.py from zpause.gsc and zpause-t7.settings.
-- Never edit by hand: change the zp_cfg calls or the README, and build.

CoD.ZPauseSettings = CoD.ZPauseSettings or {}
CoD.ZPauseSettings.Pages = {
	{
		title = "INPUT",
		hint = "zp_host_only, zp_allow_short_words, zp_button_combo ...",
		rows = {
			{
				dvar = "zp_host_only",
				key = "tJe",
				kind = "flag",
				default = "0",
				hint = "Only the host can pause or resume. Everyone else's chat command and combo are ignored, and a pause never goes to a vote. On a dedicated server there is no host, so it falls to whoever holds the first player slot. Default: OFF.",
				values = { "0", "1" },
				labels = { "OFF", "ON" },
				keys = { "ZO", "ol" }
			},
			{
				dvar = "zp_allow_short_words",
				key = "wQq",
				kind = "flag",
				default = "0",
				hint = "Also accept bare p / u / pause in chat. Off by default so normal conversation can't pause the game. Default: OFF.",
				values = { "0", "1" },
				labels = { "OFF", "ON" },
				keys = { "ZO", "ol" }
			},
			{
				dvar = "zp_button_combo",
				key = "1ex",
				kind = "flag",
				default = "1",
				hint = "Enable the button combos. Default: ON.",
				values = { "0", "1" },
				labels = { "OFF", "ON" },
				keys = { "ZO", "ol" }
			},
			{
				dvar = "zp_combo",
				key = "iTx",
				kind = "choice",
				default = "crouch_melee",
				hint = "Which combo pauses: crouch_melee, crouch_use, crouch_frag, crouch_ads, jump_melee, use_frag, frag_only, use_ads, use_attack, attack_ads. Default: CROUCH MELEE.",
				values = { "crouch_melee", "crouch_use", "crouch_frag", "crouch_ads", "jump_melee", "use_frag", "frag_only", "use_ads", "use_attack", "attack_ads" },
				labels = { "CROUCH MELEE", "CROUCH USE", "CROUCH FRAG", "CROUCH ADS", "JUMP MELEE", "USE FRAG", "FRAG ONLY", "USE ADS", "USE ATTACK", "ATTACK ADS" },
				keys = { "ug", "J8", "e8", "qp", "UM", "Vd", "cd", "DY", "xT", "4O" }
			},
			{
				dvar = "zp_button_hold_time",
				key = "ygs",
				kind = "number",
				default = "0.3",
				hint = "How long the combo must be held. Default: 0.3.",
				values = { "0.1", "0.2", "0.3", "0.5", "0.75", "1", "1.5", "2" },
				labels = { "0.1", "0.2", "0.3", "0.5", "0.75", "1", "1.5", "2" },
				keys = { "OV", "ds", "sF", "Q0", "bB", "ol", "tT", "5e" }
			},
			{
				dvar = "zp_button_combo_dead",
				key = "m6c",
				kind = "choice",
				default = "use_ads",
				hint = "Combo used while downed or spectating, when stance and melee stop registering. none = chat only. Default: USE ADS.",
				values = { "use_ads", "use_attack", "attack_ads", "use_frag", "frag_only", "none", "crouch_use", "crouch_frag", "crouch_ads", "crouch_melee" },
				labels = { "USE ADS", "USE ATTACK", "ATTACK ADS", "USE FRAG", "FRAG ONLY", "NONE", "CROUCH USE", "CROUCH FRAG", "CROUCH ADS", "CROUCH MELEE" },
				keys = { "DY", "xT", "4O", "Vd", "cd", "9t", "J8", "e8", "qp", "ug" }
			},
			{
				dvar = "zp_vote_no_combo_dead",
				key = "U8j",
				kind = "choice",
				default = "use_attack",
				hint = "The same, for a no vote. Default: USE ATTACK.",
				values = { "use_attack", "crouch_use", "crouch_frag", "crouch_ads", "crouch_melee", "use_frag", "frag_only", "use_ads", "attack_ads" },
				labels = { "USE ATTACK", "CROUCH USE", "CROUCH FRAG", "CROUCH ADS", "CROUCH MELEE", "USE FRAG", "FRAG ONLY", "USE ADS", "ATTACK ADS" },
				keys = { "xT", "J8", "e8", "qp", "ug", "Vd", "cd", "DY", "4O" }
			},
			{
				dvar = "zp_input_debug",
				key = "uEG",
				kind = "flag",
				default = "0",
				hint = "Print each player which buttons the server receives from them, for picking the two above. Default: OFF.",
				values = { "0", "1" },
				labels = { "OFF", "ON" },
				keys = { "ZO", "ol" }
			},
		}
	},
	{
		title = "VOTING (1 OF 2)",
		hint = "zp_ready_check, zp_ready_percent, zp_host_approve ...",
		rows = {
			{
				dvar = "zp_ready_check",
				key = "a4H",
				kind = "flag",
				default = "0",
				hint = "Resuming waits for the players to say they're back. Not a vote - nobody says no and it can't fail, so it needs no zp_vote, and it wins over zp_vote_unpause where both are set. Default: OFF.",
				values = { "0", "1" },
				labels = { "OFF", "ON" },
				keys = { "ZO", "ol" }
			},
			{
				dvar = "zp_ready_percent",
				key = "j6S",
				kind = "number",
				default = "100",
				hint = "How much of the room has to be ready. 100 is everybody. Default: 100.",
				values = { "25", "50", "75", "100" },
				labels = { "25", "50", "75", "100" },
				keys = { "CI", "uS", "jc", "6F" }
			},
			{
				dvar = "zp_host_approve",
				key = "OuT",
				kind = "flag",
				default = "0",
				hint = "The host pauses at once; anyone else has to ask and the host answers yes or no. It runs as a vote only the host can cast, so the yes/no input, the HUD and the timeout are a vote's. Pausing only - resuming still follows zp_vote. zp_host_only wins where both are set. Default: OFF.",
				values = { "0", "1" },
				labels = { "OFF", "ON" },
				keys = { "ZO", "ol" }
			},
			{
				dvar = "zp_vote",
				key = "cPm",
				kind = "flag",
				default = "0",
				hint = "Put pauses to a vote. See Voting. Default: OFF.",
				values = { "0", "1" },
				labels = { "OFF", "ON" },
				keys = { "ZO", "ol" }
			},
			{
				dvar = "zp_vote_min",
				key = "PXp",
				kind = "number",
				default = "2",
				hint = "Minimum yes votes, whatever the player count. Default: 2.",
				values = { "1", "2", "3", "4", "6", "8" },
				labels = { "1", "2", "3", "4", "6", "8" },
				keys = { "ol", "5e", "K1", "Xt", "39", "dO" }
			},
			{
				dvar = "zp_vote_percent",
				key = "mTM",
				kind = "number",
				default = "51",
				hint = "Percent of players who must vote yes. Default: 51.",
				values = { "25", "34", "50", "51", "67", "75", "100" },
				labels = { "25", "34", "50", "51", "67", "75", "100" },
				keys = { "CI", "yt", "uS", "f5", "oS", "jc", "6F" }
			},
			{
				dvar = "zp_vote_time",
				key = "Ifs",
				kind = "number",
				default = "30",
				hint = "Seconds a vote stays open. Default: 30.",
				values = { "10", "15", "20", "30", "45", "60", "90", "120" },
				labels = { "10", "15", "20", "30", "45", "60", "90", "120" },
				keys = { "4M", "nT", "zP", "wO", "EM", "1L", "wJ", "CH" }
			},
			{
				dvar = "zp_vote_unpause",
				key = "AFJ",
				kind = "flag",
				default = "0",
				hint = "Resuming needs a vote too. Default: OFF.",
				values = { "0", "1" },
				labels = { "OFF", "ON" },
				keys = { "ZO", "ol" }
			},
			{
				dvar = "zp_vote_hold",
				key = "0UI",
				kind = "flag",
				default = "0",
				hint = "Freeze the game while the vote runs, and resume it if the vote fails. Default: OFF.",
				values = { "0", "1" },
				labels = { "OFF", "ON" },
				keys = { "ZO", "ol" }
			},
			{
				dvar = "zp_vote_initiator_yes",
				key = "wat",
				kind = "flag",
				default = "1",
				hint = "Whoever called the vote counts as a yes. Default: ON.",
				values = { "0", "1" },
				labels = { "OFF", "ON" },
				keys = { "ZO", "ol" }
			},
			{
				dvar = "zp_vote_lockout",
				key = "MsU",
				kind = "number",
				default = "10",
				hint = "Seconds before another vote can be called after one fails. Default: 10.",
				values = { "0", "5", "10", "20", "30", "60", "120" },
				labels = { "0", "5", "10", "20", "30", "60", "120" },
				keys = { "ZO", "mG", "4M", "zP", "wO", "1L", "CH" }
			},
			{
				dvar = "zp_vote_hud",
				key = "cWH",
				kind = "flag",
				default = "1",
				hint = "Show the vote tally on screen. Default: ON.",
				values = { "0", "1" },
				labels = { "OFF", "ON" },
				keys = { "ZO", "ol" }
			},
		}
	},
	{
		title = "VOTING (2 OF 2)",
		hint = "zp_vote_show_voters, zp_vote_hud_position, zp_vote_alive_only ...",
		rows = {
			{
				dvar = "zp_vote_show_voters",
				key = "qFR",
				kind = "flag",
				default = "1",
				hint = "List each player and how they voted. Default: ON.",
				values = { "0", "1" },
				labels = { "OFF", "ON" },
				keys = { "ZO", "ol" }
			},
			{
				dvar = "zp_vote_hud_position",
				key = "y2f",
				kind = "choice",
				default = "top",
				hint = "Where the vote tally sits. See Where the HUD sits. Default: TOP.",
				values = { "top", "bottom", "middle", "left", "right" },
				labels = { "TOP", "BOTTOM", "MIDDLE", "LEFT", "RIGHT" },
				keys = { "yK", "0t", "04", "Ij", "na" }
			},
			{
				dvar = "zp_vote_alive_only",
				key = "7nF",
				kind = "flag",
				default = "1",
				hint = "Leave bled-out spectators out of the threshold and the count. Default: ON.",
				values = { "0", "1" },
				labels = { "OFF", "ON" },
				keys = { "ZO", "ol" }
			},
			{
				dvar = "zp_vote_result_time",
				key = "kn0",
				kind = "number",
				default = "2",
				hint = "Seconds the result stands on the tally after a vote resolves. 0 = clear at once. Default: 2.",
				values = { "0", "1", "2", "3", "5", "10" },
				labels = { "0", "1", "2", "3", "5", "10" },
				keys = { "ZO", "ol", "5e", "K1", "mG", "4M" }
			},
			{
				dvar = "zp_vote_no_combo",
				key = "X11",
				kind = "choice",
				default = "jump_melee",
				hint = "Combo for a no vote: jump_melee, crouch_use, crouch_frag, crouch_ads, crouch_melee. Default: JUMP MELEE.",
				values = { "jump_melee", "crouch_use", "crouch_frag", "crouch_ads", "crouch_melee", "use_frag", "frag_only", "use_ads", "use_attack", "attack_ads" },
				labels = { "JUMP MELEE", "CROUCH USE", "CROUCH FRAG", "CROUCH ADS", "CROUCH MELEE", "USE FRAG", "FRAG ONLY", "USE ADS", "USE ATTACK", "ATTACK ADS" },
				keys = { "UM", "J8", "e8", "qp", "ug", "Vd", "cd", "DY", "xT", "4O" }
			},
		}
	},
	{
		title = "TIMING",
		hint = "zp_round_pause, zp_max_pauses, zp_pause_on_disconnect ...",
		rows = {
			{
				dvar = "zp_round_pause",
				key = "NHY",
				kind = "flag",
				default = "0",
				hint = "Hold a pause until the round is over instead of freezing the game mid-horde. Asking again calls it off. Default: OFF.",
				values = { "0", "1" },
				labels = { "OFF", "ON" },
				keys = { "ZO", "ol" }
			},
			{
				dvar = "zp_max_pauses",
				key = "sHz",
				kind = "number",
				default = "0",
				hint = "How many times one match can be paused. 0 is no cap. Only a pause somebody asked for spends one - an automatic pause does not. Default: 0.",
				values = { "0", "1", "2", "3", "5", "10", "20" },
				labels = { "0", "1", "2", "3", "5", "10", "20" },
				keys = { "ZO", "ol", "5e", "K1", "mG", "4M", "zP" }
			},
			{
				dvar = "zp_pause_on_disconnect",
				key = "TqY",
				kind = "flag",
				default = "0",
				hint = "Pause when somebody drops, so whoever is left isn't overrun while they rejoin. Nothing un-pauses on its own, so zp_max_pause_time is the way out if they don't come back. Default: OFF.",
				values = { "0", "1" },
				labels = { "OFF", "ON" },
				keys = { "ZO", "ol" }
			},
			{
				dvar = "zp_countdown",
				key = "Z0G",
				kind = "number",
				default = "3",
				hint = "Seconds of 3-2-1 before play resumes. Default: 3.",
				values = { "0", "1", "2", "3", "5", "10" },
				labels = { "0", "1", "2", "3", "5", "10" },
				keys = { "ZO", "ol", "5e", "K1", "mG", "4M" }
			},
			{
				dvar = "zp_ease",
				key = "64H",
				kind = "flag",
				default = "1",
				hint = "Ease time down into the pause and back out, instead of cutting to a stop. Default: ON.",
				values = { "0", "1" },
				labels = { "OFF", "ON" },
				keys = { "ZO", "ol" }
			},
			{
				dvar = "zp_ease_time",
				key = "6ug",
				kind = "number",
				default = "0.35",
				hint = "Seconds of ramp at each end. Default: 0.35.",
				values = { "0", "0.1", "0.2", "0.35", "0.5", "0.75", "1" },
				labels = { "0", "0.1", "0.2", "0.35", "0.5", "0.75", "1" },
				keys = { "ZO", "OV", "ds", "VI", "Q0", "bB", "ol" }
			},
			{
				dvar = "zp_grace",
				key = "25U",
				kind = "number",
				default = "2",
				hint = "Seconds of invulnerability after resuming. Default: 2.",
				values = { "0", "1", "2", "3", "5", "10" },
				labels = { "0", "1", "2", "3", "5", "10" },
				keys = { "ZO", "ol", "5e", "K1", "mG", "4M" }
			},
			{
				dvar = "zp_cooldown",
				key = "BVP",
				kind = "number",
				default = "2",
				hint = "Minimum seconds between toggles. Default: 2.",
				values = { "0", "1", "2", "3", "5", "10", "30" },
				labels = { "0", "1", "2", "3", "5", "10", "30" },
				keys = { "ZO", "ol", "5e", "K1", "mG", "4M", "wO" }
			},
			{
				dvar = "zp_max_pause_time",
				key = "7HE",
				kind = "number",
				default = "0",
				hint = "Auto-resume after N seconds. 0 = unlimited. Default: 0.",
				values = { "0", "60", "120", "300", "600", "900", "1800", "3600" },
				labels = { "0", "60", "120", "300", "600", "900", "1800", "3600" },
				keys = { "ZO", "1L", "CH", "Gp", "9g", "o1", "Ez", "gH" }
			},
		}
	},
	{
		title = "WHAT GETS FROZEN",
		hint = "zp_engine_freeze, zp_drift_guard, zp_freeze_anims ...",
		rows = {
			{
				dvar = "zp_engine_freeze",
				key = "yS5",
				kind = "flag",
				default = "1",
				hint = "Use setpauseworld() and the world_is_paused flag. Default: ON.",
				values = { "0", "1" },
				labels = { "OFF", "ON" },
				keys = { "ZO", "ol" }
			},
			{
				dvar = "zp_drift_guard",
				key = "JdP",
				kind = "flag",
				default = "1",
				hint = "Snap back any AI that still manages to move. Default: ON.",
				values = { "0", "1" },
				labels = { "OFF", "ON" },
				keys = { "ZO", "ol" }
			},
			{
				dvar = "zp_freeze_anims",
				key = "wqt",
				kind = "flag",
				default = "1",
				hint = "No effect on this engine - the world freeze already stops animation. Default: ON.",
				values = { "0", "1" },
				labels = { "OFF", "ON" },
				keys = { "ZO", "ol" }
			},
			{
				dvar = "zp_silence_zombies",
				key = "XbA",
				kind = "flag",
				default = "1",
				hint = "Stop zombies growling while paused. Default: ON.",
				values = { "0", "1" },
				labels = { "OFF", "ON" },
				keys = { "ZO", "ol" }
			},
			{
				dvar = "zp_godmode",
				key = "rKa",
				kind = "flag",
				default = "1",
				hint = "Make players invulnerable while paused. Default: ON.",
				values = { "0", "1" },
				labels = { "OFF", "ON" },
				keys = { "ZO", "ol" }
			},
			{
				dvar = "zp_freeze_players",
				key = "YIW",
				kind = "flag",
				default = "1",
				hint = "Lock players in place while paused. 0 lets them walk around with their weapons down, locked again for the countdown - not recommended, because doors, the box, perks, traps and pickups can all still be used while the zombies are held. Default: ON.",
				values = { "0", "1" },
				labels = { "OFF", "ON" },
				keys = { "ZO", "ol" }
			},
			{
				dvar = "zp_control_guard",
				key = "NKi",
				kind = "flag",
				default = "1",
				hint = "Re-apply the player freeze every tick, so a map script can't hand controls back mid-pause. Default: ON.",
				values = { "0", "1" },
				labels = { "OFF", "ON" },
				keys = { "ZO", "ol" }
			},
			{
				dvar = "zp_freeze_clock",
				key = "oiy",
				kind = "flag",
				default = "1",
				hint = "Hold the match timer. Default: ON.",
				values = { "0", "1" },
				labels = { "OFF", "ON" },
				keys = { "ZO", "ol" }
			},
			{
				dvar = "zp_freeze_powerups",
				key = "1s5",
				kind = "flag",
				default = "1",
				hint = "Stop ground powerups timing out. Default: ON.",
				values = { "0", "1" },
				labels = { "OFF", "ON" },
				keys = { "ZO", "ol" }
			},
			{
				dvar = "zp_freeze_effects",
				key = "ejR",
				kind = "flag",
				default = "1",
				hint = "Hold insta-kill / double-points countdowns. Default: ON.",
				values = { "0", "1" },
				labels = { "OFF", "ON" },
				keys = { "ZO", "ol" }
			},
			{
				dvar = "zp_freeze_bleedout",
				key = "88Y",
				kind = "flag",
				default = "1",
				hint = "Stop downed players bleeding out. Default: ON.",
				values = { "0", "1" },
				labels = { "OFF", "ON" },
				keys = { "ZO", "ol" }
			},
		}
	},
	{
		title = "PRESENTATION (1 OF 2)",
		hint = "zp_hud, zp_blackout, zp_blackout_alpha ...",
		rows = {
			{
				dvar = "zp_hud",
				key = "Vle",
				kind = "flag",
				default = "1",
				hint = "Draw the pause block at all. The vote HUD is separate and still draws. Default: ON.",
				values = { "0", "1" },
				labels = { "OFF", "ON" },
				keys = { "ZO", "ol" }
			},
			{
				dvar = "zp_blackout",
				key = "reG",
				kind = "flag",
				default = "1",
				hint = "Dim everyone's screen while paused, which keeps the pause text readable over a bright skybox. Raise zp_blackout_alpha for the anti-scouting blackout this used to be. Default: ON.",
				values = { "0", "1" },
				labels = { "OFF", "ON" },
				keys = { "ZO", "ol" }
			},
			{
				dvar = "zp_blackout_alpha",
				key = "4Ve",
				kind = "number",
				default = "0.2",
				hint = "How far it dims. 0.2 is a light darkening; 1 is fully black. Default: 0.2.",
				values = { "0.1", "0.2", "0.35", "0.5", "0.65", "0.8", "1" },
				labels = { "0.1", "0.2", "0.35", "0.5", "0.65", "0.8", "1" },
				keys = { "OV", "ds", "VI", "Q0", "8x", "D8", "ol" }
			},
			{
				dvar = "zp_show_hint",
				key = "1hX",
				kind = "flag",
				default = "1",
				hint = "Tell players how to pause when they spawn. Default: ON.",
				values = { "0", "1" },
				labels = { "OFF", "ON" },
				keys = { "ZO", "ol" }
			},
			{
				dvar = "zp_hud_position",
				key = "5s1",
				kind = "choice",
				default = "center",
				hint = "Where the pause banner sits. See Where the HUD sits. Default: CENTER.",
				values = { "center", "top", "bottom", "middle", "left", "right" },
				labels = { "CENTER", "TOP", "BOTTOM", "MIDDLE", "LEFT", "RIGHT" },
				keys = { "i0", "yK", "0t", "04", "Ij", "na" }
			},
			{
				dvar = "zp_hud_binds",
				key = "SVG",
				kind = "flag",
				default = "1",
				hint = "Draw combos as each player's bound buttons instead of words. Default: ON.",
				values = { "0", "1" },
				labels = { "OFF", "ON" },
				keys = { "ZO", "ol" }
			},
			{
				dvar = "zp_hud_glow",
				key = "Zo0",
				kind = "flag",
				default = "1",
				hint = "Black glow behind the HUD text, to carry it over a bright skybox. Default: ON.",
				values = { "0", "1" },
				labels = { "OFF", "ON" },
				keys = { "ZO", "ol" }
			},
			{
				dvar = "zp_hud_panel",
				key = "6pU",
				kind = "flag",
				default = "0",
				hint = "Black slab behind the whole block. Heavier than the glow. Default: OFF.",
				values = { "0", "1" },
				labels = { "OFF", "ON" },
				keys = { "ZO", "ol" }
			},
			{
				dvar = "zp_hud_panel_alpha",
				key = "rZp",
				kind = "number",
				default = "0.45",
				hint = "How opaque that slab is. 1 is solid black. Default: 0.45.",
				values = { "0.2", "0.35", "0.45", "0.6", "0.8", "1" },
				labels = { "0.2", "0.35", "0.45", "0.6", "0.8", "1" },
				keys = { "ds", "VI", "00", "fN", "D8", "ol" }
			},
			{
				dvar = "zp_hud_panel_width",
				key = "JUs",
				kind = "number",
				default = "340",
				hint = "How wide it is, in HUD units. Default: 340.",
				values = { "240", "300", "340", "400", "480", "560", "640" },
				labels = { "240", "300", "340", "400", "480", "560", "640" },
				keys = { "HU", "Gp", "Cj", "zN", "pA", "mZ", "5a" }
			},
			{
				dvar = "zp_hud_timer",
				key = "5Ts",
				kind = "flag",
				default = "1",
				hint = "Show who paused and how long it has been. Minutes, not mm:ss - see below. Default: ON.",
				values = { "0", "1" },
				labels = { "OFF", "ON" },
				keys = { "ZO", "ol" }
			},
			{
				dvar = "zp_blur",
				key = "5qJ",
				kind = "flag",
				default = "1",
				hint = "Blur everyone's screen while paused. Clears when play resumes. Default: ON.",
				values = { "0", "1" },
				labels = { "OFF", "ON" },
				keys = { "ZO", "ol" }
			},
		}
	},
	{
		title = "PRESENTATION (2 OF 2)",
		hint = "zp_blur_amount, zp_pause_sound, zp_countdown_sound ...",
		rows = {
			{
				dvar = "zp_blur_amount",
				key = "kq4",
				kind = "number",
				default = "2",
				hint = "Blur strength. 4 is the blur the game runs when you buy a perk. Default: 2.",
				values = { "0.5", "1", "1.5", "2", "3", "4", "6" },
				labels = { "0.5", "1", "1.5", "2", "3", "4", "6" },
				keys = { "Q0", "ol", "tT", "5e", "K1", "Xt", "39" }
			},
			{
				dvar = "zp_pause_sound",
				key = "ujM",
				kind = "choice",
				default = "zmb_bgb_killingtime_start",
				hint = "Played when the game is paused. none = silent. Default: KILLING TIME START.",
				values = { "zmb_bgb_killingtime_start", "none" },
				labels = { "KILLING TIME START", "NONE" },
				keys = { "HD", "9t" }
			},
			{
				dvar = "zp_countdown_sound",
				key = "F89",
				kind = "choice",
				default = "zmb_finalcountdown_timer_marker",
				hint = "Played on each countdown tick. none = silent. Default: COUNTDOWN MARKER.",
				values = { "zmb_finalcountdown_timer_marker", "none" },
				labels = { "COUNTDOWN MARKER", "NONE" },
				keys = { "xV", "9t" }
			},
			{
				dvar = "zp_resume_sound",
				key = "VAW",
				kind = "choice",
				default = "zmb_bgb_killingtime_end",
				hint = "Played when play resumes. none = silent. Default: KILLING TIME END.",
				values = { "zmb_bgb_killingtime_end", "none" },
				labels = { "KILLING TIME END", "NONE" },
				keys = { "q3", "9t" }
			},
		}
	},
}
